apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  template:
    metadata:
      name: worker-pod
    spec:
      containers:
      - name: worker
        image: workerimage
        imagePullPolicy: Never
      restartPolicy: Never