apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Cluster-Client-Ip $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
        }
spec:
  rules:
    - host: "hw1.edgerock1.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: phoenix-svc
                port:
                  number: 4000

    - host: "hw2.edgerock1.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: phoenix-svc
                port:
                  number: 4000
