apiVersion: v1
kind: Service
metadata:  
  name: ephoenix-deployment
spec:
  ports:
  - nodePort: 30545
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: phoenix
  type: LoadBalancer