apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephoenix-deployment
spec:
  selector:
    matchLabels:
      app: phoenix
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      containers:
      - name: ephoenix
        image: phoeniximage
        args: ["start"]
        imagePullPolicy: Never
        env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        ports:
          - name: phoenixport
            containerPort: 4000
            protocol: TCP