apiVersion: apps/v1
kind: Deployment
metadata:
  name: erouter-deployment
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: worker
        deployment: cluster
    spec:
      containers:
        - name: erouter
          image: edgerock/conts:routerimage4
          args: ["start"]
          env:
          env:
            - name: TZ
              value: America/Chicago
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: epmd
              containerPort: 4369
              protocol: TCP
